### ISSUE TITLE
Deprecation warning for jsonschema @ 4.0.0

### ISSUE THREAD

**Issue by nikitagashkov** [python-openapi/openapi-spec-validator#134]
Hello @p1c2u, thanks for your library. I've recently performed a scheduled dependencies upgrade and encountered the following warning:

```
...

  /Users/.../lib/python3.9/site-packages/jsonschema/validators.py:190: DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).iter_errors(...) instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

Looks like `jsonschema` starting from v4.0.0 deprecates one of theirs API used: https://github.com/Julian/jsonschema/releases/tag/v4.0.0

**Comment by p1c2u** [comment]
It will be fixed in version 0.5.x which is dependent on jsonschema4+
Version 0.4.x will support jsonschema 3 and 4.
