### ISSUE TITLE
Please update for `openapi-schema-validator` 0.4

### ISSUE THREAD

**Issue by kloczek** [python-openapi/openapi-spec-validator#159]
https://github.com/p1c2u/openapi-spec-validator/blob/a29b4f9dd64eed13e2f1c1e046d7b6cfe89a5b0c/pyproject.toml#L34-L36

**Comment by p1c2u** [comment]
Why allow prerelease?  What's the reason? Version [0.3.0](https://github.com/p1c2u/openapi-schema-validator/releases/tag/0.3.0) was released already.

**Comment by kloczek** [comment]
Wrong link ..
https://github.com/p1c2u/openapi-spec-validator/blob/0.4.0/pyproject.toml#L34-L36

**Comment by p1c2u** [comment]
openapi-spec-validator 0.4.x works with openapi-schema-validator 0.2.x only


https://github.com/p1c2u/openapi-core/issues/296#issuecomment-1020239222
