### ISSUE TITLE
AttributeError: module 'jsonschema._utils' has no attribute 'load_schema'

### ISSUE THREAD

**Issue by nmoreaud** [python-openapi/openapi-spec-validator#201]
jsonschema 4.18.0a1 breaks compatibility, I can't use pytest on my project.
See also https://github.com/python-openapi/openapi-schema-validator/issues/70

**Comment by p1c2u** [comment]
Hi @nmoreaud 

thanks for the report. We will need to lock deps to supporting version (<4.18).
