### ISSUE TITLE
Type of "Any property starting with x- is valid."

### ISSUE THREAD

**Issue by KES777** [python-openapi/openapi-spec-validator#206]
https://github.com/python-openapi/openapi-spec-validator/blob/master/openapi_spec_validator/resources/schemas/v3.0.0/schema.json#L1225

Should it be `anyOf` instead of `oneOf`.
In my case validation fails, because `1` is looks like number or string:
`x-my-prop: 1`.

Actually schema should not care which value is there.

**Comment by p1c2u** [comment]
Hi @KES777 

linked schema is no longer used. Please check the latest version and if your issue persist re-open the ticket.
