### ISSUE TITLE
Cannot import _legacy_validators

### ISSUE THREAD

**Issue by rochacbruno** [python-openapi/openapi-spec-validator#280]
REF https://github.com/python-jsonschema/jsonschema/commit/931323043b4409a0416f373403bfb52408fc282f
![2023-09-20_17-20](https://github.com/python-openapi/openapi-spec-validator/assets/458654/9254fd62-0b4e-450f-9d7d-9c6c79d57eed)

File was renamed on latest `jsonschema` released 2 hours ago

**Comment by rochacbruno** [comment]
Reported on https://github.com/python-openapi/openapi-schema-validator/issues/131

**Comment by p1c2u** [comment]
New openapi-schema-validator version was released hence closing
